language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "3.9"
    - "3.9-dev"
install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
before_script:
    - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
script:
    - make test
    - make lint
    - make format && git diff --quiet HEAD
